---
resource_types:
- name: concourse-bitbucket-pipelines-discovery
  type: docker-image
  source:
    repository: wayofthepie/bitbucket-multibranch-resource

resources:
- name: multibranch
  type: concourse-bitbucket-pipelines-discovery
  check_every: 10s
  source:
    url: http://192.168.1.5:7990
    username: admin
    password: admin
    project: TEST
    repo: test

jobs:
- name: create-pipelines
  plan:
    - get: multibranch
    - put: multibranch


